# Pandas Dataframe

In [1]:
import pandas as pd

#empty df:

In [2]:
d = pd.DataFrame()

In [3]:
d

Empty DataFrame
Columns: []
Index: []

In [4]:
d.shape

(0, 0)

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Empty DataFrame

In [6]:
country = ["BD","India","Pak","Nepal","Sri"]

In [7]:
country

['BD', 'India', 'Pak', 'Nepal', 'Sri']

In [8]:
saarc = pd.DataFrame(country)

In [9]:
saarc

       0
0     BD
1  India
2    Pak
3  Nepal
4    Sri

In [10]:
saarc.shape

(5, 1)

In [11]:
saarc = pd.DataFrame(country, columns = ['countryname'], index = ['n1','n2','n3','n4','n5'])
saarc

   countryname
n1          BD
n2       India
n3         Pak
n4       Nepal
n5         Sri

In [12]:
country2 = ['America','Germany','England','Ireland','Norway']
country2

['America', 'Germany', 'England', 'Ireland', 'Norway']

In [13]:
who = pd.DataFrame(country2, columns = ['countryname2'])

In [14]:
who

  countryname2
0      America
1      Germany
2      England
3      Ireland
4       Norway

In [15]:
combind = pd.DataFrame(zip(country,country2), columns = ["saarc","who"],index = ["c1",'c2','c3','c4','c5'])
combind

    saarc      who
c1     BD  America
c2  India  Germany
c3    Pak  England
c4  Nepal  Ireland
c5    Sri   Norway

In [16]:
combind.shape

(5, 2)

In [17]:
L = [["mango","banana","lichy"],["rose","bela","lily"],["potato","bean","chili"]]
L

[['mango', 'banana', 'lichy'],
 ['rose', 'bela', 'lily'],
 ['potato', 'bean', 'chili']]

In [18]:
M = pd.DataFrame(L, index=['fruits','flowers','veg'],columns= ['c1','c2','c3'])

In [19]:
M

             c1      c2     c3
fruits    mango  banana  lichy
flowers    rose    bela   lily
veg      potato    bean  chili

In [20]:
std = {
     "student1": {
    "name": "Saikat Sarker",
    "grade" : 11,
     "roll": 10,
     "Id No": 123450
    },
    "student2": {
    "name": "Surjo Sarker",
    "class": "10th",
     "roll": 11,
     "Id No": 123460
    },
}

In [21]:
std

{'student1': {'name': 'Saikat Sarker',
  'grade': 11,
  'roll': 10,
  'Id No': 123450},
 'student2': {'name': 'Surjo Sarker',
  'class': '10th',
  'roll': 11,
  'Id No': 123460}}

In [22]:
s = pd.DataFrame(std)

In [23]:
s

            student1      student2
name   Saikat Sarker  Surjo Sarker
grade             11           NaN
roll              10            11
Id No         123450        123460
class            NaN          10th

In [24]:
import pandas as pd

In [25]:
s = pd.read_excel('std.xlsx')           #for csv file: pd.read_csv('filename.csv')
s

     Name Class  Roll      ID Country
0   Karim  11th     1    1111      BD
1   Rahim  12th     2    1234      BD
2   Salam  10th     3  123545     Pak
3  Barkat   9th     4    5643   India
4  Jobbar  10th     5    1123     pak

In [26]:
df = pd.read_excel('VFA.xlsx')

In [27]:
df

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
20,Log0024879,A87FEMOTNWOVPANNOT,NaN,A87FE,NaN,A87FE,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,60,Brand asked to remake P2 n maintain the spec,web-form@smartsheet.com,2023-01-09 22:29:05,novita_brilianty@vfc.com,NaN,2023-02-18 05:41:09,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [28]:
df.head()

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [29]:
df.tail()

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [30]:
df.head(10)

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [31]:
df.tail(10)

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
20,Log0024879,A87FEMOTNWOVPANNOT,NaN,A87FE,NaN,A87FE,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,60,Brand asked to remake P2 n maintain the spec,web-form@smartsheet.com,2023-01-09 22:29:05,novita_brilianty@vfc.com,NaN,2023-02-18 05:41:09,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [32]:
df.shape

(29, 72)

In [33]:
rows,colums = df.shape

In [34]:
rows

29

In [35]:
colums

72

In [36]:
df.values

array([['Log0024795', 'A82V2SNTNWOVOUTNOT', nan, ..., nan, nan, nan],
       ['Log0024758', 'A86QPMOTNWOVSHINOT', nan, ..., nan, nan, nan],
       ['Log0024745', 'A87Y7SNTNWOVPANSEA', nan, ..., nan, nan, nan],
       ...,
       ['Log0024796', 'A82WDSNTNWOVOUTNOT', nan, ..., nan, nan, nan],
       ['Log0024621', 'A86NZMOTNWOVOUTNOT', nan, ..., nan, nan, nan],
       ['Log0024619', 'A7WYOSNTNWOVOUTFIL', nan, ..., nan, nan, nan]],
      dtype=object)

In [37]:
df.columns

Index(['Row ID', 'Unique Style Identifier', 'New or Existing Style',
       'New Style', 'Existing Style', 'Style', 'Season', 'Date of submission',
       'VF Regional Location', 'SBU_New', 'SBU', 'Brand_New', 'Brand',
       'Product Main Category_New', 'Product Main Category',
       'Product Sub Category_New', 'Product Sub Category',
       'Special construction_New', 'Special construction', 'Complexity',
       'Style Status', 'FFC - Factory Name', 'Factory FFC', 'Factory Name',
       'Country of Origin', 'Vendor FFC', 'Vendor Name', 'Sample type',
       'E-pattern & pattern overlay', 'Measurement sheet',
       'Sample checklist / BOM', 'Reference Sample', 'Packaging',
       'Remarks by Sourcing', 'Sample approval owned by',
       'Submission form updated by', 'TD name', 'TD Email', 'CFT Name',
       'CFT email', 'TVCP', 'TVCP Remarks', 'Approval Result',
       'Brand Approval Result', 'Sample Out Date', 'Review Type', 'Dropped',
       'Upgraded to PPS', 'Fit balance/Pattern', 'Fit balance/Patten Score',
       'Measurement', 'Measurement Score', 'Workmanship', 'Workmanship Score',
       'Construction', 'Construction Score', 'All previous comments actioned',
       'Comment Action Score', 'Action Taken By TD',
       'Overall accuracy of sample comment form', 'Sample Checklist Score',
       'If not OK, please select main reason(s)', 'Overall Score',
       'Remarks by TD', 'Created By', 'Created', 'Modified By', 'Complex',
       'Modified', 'Submission By (Email)', 'Submission By (Name)',
       'CFT Name_Workaround'],
      dtype='object')

In [38]:
df.index

RangeIndex(start=0, stop=29, step=1)

In [39]:
s.values

array([['Karim', '11th', 1, 1111, 'BD'],
       ['Rahim', '12th', 2, 1234, 'BD'],
       ['Salam', '10th', 3, 123545, 'Pak'],
       ['Barkat', '9th', 4, 5643, 'India'],
       ['Jobbar', '10th', 5, 1123, 'pak']], dtype=object)

In [40]:
df.head()

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [41]:
df.Style

0                         A82V2
1                         A86QP
2                         A87Y7
3                         A878R
4                         A87XD
5                         A87XE
6                         A86NT
7                         A86P0
8                         A5J96
9       NA4HCT-ACALMAR W VEST 6
10               NA4HPO-A-HURON
11           NA4HS7-A-KENDALL W
12             NA4HXC-OBEY VEST
13    NA4H9Y-A-COUBERTIN ANORAK
14        NA4GE9-NORTHFARER 2.0
15      NA4HXD-OBEY EPOCH SHELL
16                        A86NW
17                        A86NV
18                        A86P3
19                        A86P2
20                        A87FE
21                        A86R6
22                        A87XF
23     NA4HTR-RAINFOREST OP S W
24         NA4HRW-A-RAYMI FZH W
25          A-HURON VEST-NA4HPN
26                        A82WD
27                        A86NZ
28                        A7WYO
Name: Style, dtype: object

In [42]:
df[['Row ID']]

        Row ID
0   Log0024795
1   Log0024758
2   Log0024745
3   Log0024737
4   Log0025008
5   Log0024957
6   Log0025126
7   Log0025124
8   Log0025077
9   Log0025139
10  Log0024988
11  Log0024987
12  Log0024986
13  Log0024985
14  Log0024984
15  Log0024983
16  Log0024887
17  Log0024886
18  Log0024882
19  Log0024881
20  Log0024879
21  Log0024878
22  Log0024873
23  Log0024833
24  Log0024829
25  Log0024827
26  Log0024796
27  Log0024621
28  Log0024619

In [43]:
df.Season.head(10)

0    FA23
1    SP24
2    FA24
3    SP24
4    FA24
5    FA24
6    SP24
7    SP24
8    FA23
9    FW23
Name: Season, dtype: object

In [44]:
df[['Date of submission']].head(12)

   Date of submission
0          2023-01-09
1          2023-01-06
2          2023-01-06
3          2023-01-06
4          2023-01-12
5          2023-01-11
6          2023-01-13
7          2023-01-13
8          2023-01-12
9          2023-01-13
10         2023-01-11
11         2023-01-11

In [45]:
df[['Row ID','VF Regional Location','Date of submission']].head(8)

       Row ID VF Regional Location Date of submission
0  Log0024795            Indonesia         2023-01-09
1  Log0024758            Indonesia         2023-01-06
2  Log0024745            Indonesia         2023-01-06
3  Log0024737            Indonesia         2023-01-06
4  Log0025008            Indonesia         2023-01-12
5  Log0024957            Indonesia         2023-01-11
6  Log0025126            Indonesia         2023-01-13
7  Log0025124            Indonesia         2023-01-13

In [46]:
df['Date of submission'].sort_values()

28   2023-01-04
27   2023-01-04
1    2023-01-06
2    2023-01-06
3    2023-01-06
26   2023-01-09
25   2023-01-09
24   2023-01-09
23   2023-01-09
0    2023-01-09
19   2023-01-10
22   2023-01-10
21   2023-01-10
20   2023-01-10
18   2023-01-10
16   2023-01-10
17   2023-01-10
5    2023-01-11
10   2023-01-11
13   2023-01-11
12   2023-01-11
11   2023-01-11
15   2023-01-11
14   2023-01-11
8    2023-01-12
4    2023-01-12
9    2023-01-13
7    2023-01-13
6    2023-01-13
Name: Date of submission, dtype: datetime64[ns]

In [47]:
df['Row ID'].sort_values(ascending=False)

9     Log0025139
6     Log0025126
7     Log0025124
8     Log0025077
4     Log0025008
10    Log0024988
11    Log0024987
12    Log0024986
13    Log0024985
14    Log0024984
15    Log0024983
5     Log0024957
16    Log0024887
17    Log0024886
18    Log0024882
19    Log0024881
20    Log0024879
21    Log0024878
22    Log0024873
23    Log0024833
24    Log0024829
25    Log0024827
26    Log0024796
0     Log0024795
1     Log0024758
2     Log0024745
3     Log0024737
27    Log0024621
28    Log0024619
Name: Row ID, dtype: object

In [48]:
df.sort_values('Row ID',ascending =  False ).head(15)

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [49]:
df.describe()

,New or Existing Style,Existing Style,Factory FFC,Vendor FFC,Packaging,Remarks by Sourcing,TVCP Remarks,Brand Approval Result,Dropped,Upgraded to PPS,...,Measurement Score,Workmanship Score,Construction Score,Comment Action Score,Sample Checklist Score,Overall Score,Complex,Submission By (Email),Submission By (Name),CFT Name_Workaround
count,0.0,0.0,29.000000,29.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,29.000000,29.000000,29.0,29.000000,29.000000,29.000000,0.0,0.0,0.0,0.0
mean,NaN,NaN,40325.448276,20881.827586,NaN,NaN,NaN,NaN,NaN,NaN,...,19.310345,16.551724,20.0,17.931034,17.931034,111.034483,NaN,NaN,NaN,NaN
std,NaN,NaN,9277.221658,5593.345141,NaN,NaN,NaN,NaN,NaN,NaN,...,3.713907,7.688517,0.0,6.198681,6.198681,17.391465,NaN,NaN,NaN,NaN
min,NaN,NaN,15396.000000,12722.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,20.0,0.000000,0.000000,60.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,35577.000000,12722.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000000,20.000000,20.0,20.000000,20.000000,100.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,35577.000000,24582.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000000,20.000000,20.0,20.000000,20.000000,120.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,50017.000000,24582.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000000,20.000000,20.0,20.000000,20.000000,120.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,63503.000000,26163.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,20.000000,20.000000,20.0,20.000000,20.000000,120.000000,NaN,NaN,NaN,NaN

In [50]:
df.corr()

C:\Users\T\AppData\Local\Temp\ipykernel_6292\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,New or Existing Style,Existing Style,Factory FFC,Vendor FFC,Packaging,Remarks by Sourcing,TVCP Remarks,Brand Approval Result,Dropped,Upgraded to PPS,...,Measurement Score,Workmanship Score,Construction Score,Comment Action Score,Sample Checklist Score,Overall Score,Complex,Submission By (Email),Submission By (Name),CFT Name_Workaround
New or Existing Style,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Existing Style,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Factory FFC,NaN,NaN,1.000000,-0.649947,NaN,NaN,NaN,NaN,NaN,NaN,...,0.098441,0.160198,NaN,0.427608,0.427608,0.417681,NaN,NaN,NaN,NaN
Vendor FFC,NaN,NaN,-0.649947,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.127231,-0.297907,NaN,-0.184477,-0.184477,-0.317543,NaN,NaN,NaN,NaN
Packaging,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Remarks by Sourcing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TVCP Remarks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand Approval Result,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dropped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upgraded to PPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fit balance/Patten Score,NaN,NaN,0.098441,-0.127231,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,-0.086258,NaN,-0.064194,0.556349,0.564376,NaN,NaN,NaN,NaN
Measurement Score,NaN,NaN,0.098441,-0.127231,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,-0.086258,NaN,-0.064194,0.556349,0.564376,NaN,NaN,NaN,NaN
Workmanship Score,NaN,NaN,0.160198,-0.297907,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.086258,1.000000,NaN,0.444458,0.144707,0.615236,NaN,NaN,NaN,NaN
Construction Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Comment Action Score,NaN,NaN,0.427608,-0.184477,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.064194,0.444458,NaN,1.000000,0.256410,0.616882,NaN,NaN,NaN,NaN
Sample Checklist Score,NaN,NaN,0.427608,-0.184477,NaN,NaN,NaN,NaN,NaN,NaN,...,0.556349,0.144707,NaN,0.256410,1.000000,0.749398,NaN,NaN,NaN,NaN
Overall Score,NaN,NaN,0.417681,-0.317543,NaN,NaN,NaN,NaN,NaN,NaN,...,0.564376,0.615236,NaN,0.616882,0.749398,1.000000,NaN,NaN,NaN,NaN
Complex,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Submission By (Email),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Submission By (Name),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CFT Name_Workaround,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df['Overall Score']>100

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20    False
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
Name: Overall Score, dtype: bool

In [52]:
df[df['Overall Score']>100]

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [53]:
df[df['VF Regional Location'] =='Indonesia']

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
20,Log0024879,A87FEMOTNWOVPANNOT,NaN,A87FE,NaN,A87FE,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,60,Brand asked to remake P2 n maintain the spec,web-form@smartsheet.com,2023-01-09 22:29:05,novita_brilianty@vfc.com,NaN,2023-02-18 05:41:09,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [54]:
df[(df['VF Regional Location'] == 'Indonesia') | (df['VF Regional Location'] == 'Cambodia')]

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
20,Log0024879,A87FEMOTNWOVPANNOT,NaN,A87FE,NaN,A87FE,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,60,Brand asked to remake P2 n maintain the spec,web-form@smartsheet.com,2023-01-09 22:29:05,novita_brilianty@vfc.com,NaN,2023-02-18 05:41:09,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [55]:
df[df['VF Regional Location'].isin(['Cambodia','Indonesia'])]

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
0,Log0024795,A82V2SNTNWOVOUTNOT,NaN,A82V2,NaN,A82V2,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:24:01,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
1,Log0024758,A86QPMOTNWOVSHINOT,NaN,A86QP,NaN,A86QP,SP24,2023-01-06,Indonesia,Mountain lifestyle,...,100,NaN,web-form@smartsheet.com,2023-01-06 01:26:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
2,Log0024745,A87Y7SNTNWOVPANSEA,NaN,A87Y7,NaN,A87Y7,FA24,2023-01-06,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-05 22:59:53,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
3,Log0024737,A878RMFTNWOVPANNOT,NaN,A878R,NaN,A878R,SP24,2023-01-06,Indonesia,MFO,...,100,NaN,web-form@smartsheet.com,2023-01-05 19:11:35,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
4,Log0025008,A87XDMOTNWOVLIGSEA,NaN,A87XD,NaN,A87XD,FA24,2023-01-12,Indonesia,Mountain lifestyle,...,100,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-11 20:18:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
5,Log0024957,A87XEMOTNWOVBIBSEA,NaN,A87XE,NaN,A87XE,FA24,2023-01-11,Indonesia,Mountain lifestyle,...,80,Brand ask to send the sample to keep P1 fittin...,web-form@smartsheet.com,2023-01-10 23:11:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
6,Log0025126,A86NTMOTNWOVOUTNOT,NaN,A86NT,NaN,A86NT,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,100,NaN,web-form@smartsheet.com,2023-01-12 21:51:24,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
7,Log0025124,A86P0MOTNWOVLIGSEA,NaN,A86P0,NaN,A86P0,SP24,2023-01-13,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-12 20:36:47,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
8,Log0025077,A5J96MOTNWOVPANNOT,NaN,A5J96,NaN,A5J96,FA23,2023-01-12,Indonesia,MOUNTAIN ESSENTIALS,...,60,NaN,web-form@smartsheet.com,2023-01-12 01:11:49,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
16,Log0024887,A86NWMOTNWOVOUTNOT,NaN,A86NW,NaN,A86NW,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:42:05,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
17,Log0024886,A86NVMOTNWOVOUTNOT,NaN,A86NV,NaN,A86NV,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:31:12,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
18,Log0024882,A86P3MOTNWOVOUTNOT,NaN,A86P3,NaN,A86P3,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:22:45,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
19,Log0024881,A86P2MOTNWOVOUTNOT,NaN,A86P2,NaN,A86P2,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 23:12:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
20,Log0024879,A87FEMOTNWOVPANNOT,NaN,A87FE,NaN,A87FE,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,60,Brand asked to remake P2 n maintain the spec,web-form@smartsheet.com,2023-01-09 22:29:05,novita_brilianty@vfc.com,NaN,2023-02-18 05:41:09,NaN,NaN,NaN
21,Log0024878,A86R6MOTNWOVOUTNOT,NaN,A86R6,NaN,A86R6,SP24,2023-01-10,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-09 22:14:06,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
22,Log0024873,A87XFSNTNWOVOUTSEA,NaN,A87XF,NaN,A87XF,FA24,2023-01-10,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-09 20:49:21,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
26,Log0024796,A82WDSNTNWOVOUTNOT,NaN,A82WD,NaN,A82WD,FA23,2023-01-09,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-08 18:27:11,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
27,Log0024621,A86NZMOTNWOVOUTNOT,NaN,A86NZ,NaN,A86NZ,SP24,2023-01-04,Indonesia,MOUNTAIN ESSENTIALS,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:38:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
28,Log0024619,A7WYOSNTNWOVOUTFIL,NaN,A7WYO,NaN,A7WYO,FW23,2023-01-04,Indonesia,Snowsport,...,120,NaN,web-form@smartsheet.com,2023-01-03 20:32:50,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN

In [56]:
df[df['VF Regional Location'].isin(['Cambodia'])]

,Row ID,Unique Style Identifier,New or Existing Style,New Style,Existing Style,Style,Season,Date of submission,VF Regional Location,SBU_New,...,Overall Score,Remarks by TD,Created By,Created,Modified By,Complex,Modified,Submission By (Email),Submission By (Name),CFT Name_Workaround
9,Log0025139,NA4HCT-ACALMAR W VEST 6CONAWOVVESNOT,NaN,NA4HCT-ACALMAR W VEST 6,NaN,NA4HCT-ACALMAR W VEST 6,FW23,2023-01-13,Cambodia,Core,...,100,Return to rectify and will have further review,web-form@smartsheet.com,2023-01-13 00:21:30,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
10,Log0024988,NA4HPO-A-HURONCONAWOVVESNOT,NaN,NA4HPO-A-HURON,NaN,NA4HPO-A-HURON,SS24,2023-01-11,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-11 07:22:44,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
11,Log0024987,NA4HS7-A-KENDALL WCONAWOVLIGNOT,NaN,NA4HS7-A-KENDALL W,NaN,NA4HS7-A-KENDALL W,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:20:46,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
12,Log0024986,NA4HXC-OBEY VESTCONAWOVVESNOT,NaN,NA4HXC-OBEY VEST,NaN,NA4HXC-OBEY VEST,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:12:41,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
13,Log0024985,NA4H9Y-A-COUBERTIN ANORAKCONAWOVLIGNOT,NaN,NA4H9Y-A-COUBERTIN ANORAK,NaN,NA4H9Y-A-COUBERTIN ANORAK,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:10:55,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
14,Log0024984,NA4GE9-NORTHFARER 2.0CONAWOVLIGNOT,NaN,NA4GE9-NORTHFARER 2.0,NaN,NA4GE9-NORTHFARER 2.0,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:06:27,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
15,Log0024983,NA4HXD-OBEY EPOCH SHELLCONAWOVLIGSEA,NaN,NA4HXD-OBEY EPOCH SHELL,NaN,NA4HXD-OBEY EPOCH SHELL,SS24,2023-01-11,Cambodia,Core,...,120,Ok to ship,web-form@smartsheet.com,2023-01-11 07:04:10,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
23,Log0024833,NA4HTR-RAINFOREST OP S WCONAWOVLIGSEA,NaN,NA4HTR-RAINFOREST OP S W,NaN,NA4HTR-RAINFOREST OP S W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:48:08,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
24,Log0024829,NA4HRW-A-RAYMI FZH WCONAWOVLIGNOT,NaN,NA4HRW-A-RAYMI FZH W,NaN,NA4HRW-A-RAYMI FZH W,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:18:40,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN
25,Log0024827,A-HURON VEST-NA4HPNCONAWOVVESNOT,NaN,A-HURON VEST-NA4HPN,NaN,A-HURON VEST-NA4HPN,SS24,2023-01-09,Cambodia,Core,...,120,OK to ship,web-form@smartsheet.com,2023-01-09 00:13:28,automation@smartsheet.com,NaN,2023-01-16 00:05:16,NaN,NaN,NaN